superheros/superheros/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheros_app/', include('superheros_app.urls')),
    path('', RedirectView.as_view(url='/superheros_app/'))
]

superheros/superheros_app/urls.py
from django.urls import path
from . import views


app_name = 'superheros_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:superheros_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('update/<int:superheros_id>/', views.update, name='update'),
    path('kryptonite/<int:superheros_id>', views.kryptonite, name='kryptonite')
]

superheros/superheros_app/models.py
from django.db import models
# Create your models here.


class superhero_app(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_superhero_ability = models.CharField(max_length=50)
    secondary_superhero_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superheros/superheros_app/views.py
from django.shortcuts import render
from .models import superhero_app
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)
from django.forms import ModelForm
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import redirect
# Create your views here.


def index(request):
    all_superheros_app = superhero_app.objects.all()
    context = {
        'all_superheros_app': all_superheros_app
    }
    return render(request, 'superheros_app/index.html', context)


def detail(request, superheros_id):
    single_superheros_app = superhero_app.objects.get(id=superheros_id)
    context = {
        'single_superheros_app': single_superheros_app
    }
    return render(request, 'superheros_app/detail.html', context)


def update(request, superheros_id):
    single_superheros_app = superhero_app.objects.get(id=superheros_id)
    context = {
        'single_superheros_app': single_superheros_app
    }
    if request.method == 'POST':
        single_superheros_app.name = request.POST.get('name')
        single_superheros_app.alter_ego = request.POST.get('alter_ego')
        single_superheros_app.primary_superhero_ability = request.POST.get('primary_superhero_ability')
        single_superheros_app.secondary_superhero_ability = request.POST.get('secondary_superhero_ability')
        single_superheros_app.catchphrase = request.POST.get('catchphrase')
        single_superheros_app.save()
        return HttpResponseRedirect(reverse('superheros_app:index'))
    else:
        return render(request, 'superheros_app/update.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superhero_ability = request.POST.get('primary_superhero_ability')
        secondary_superhero_ability = request.POST.get('secondary_superhero_ability')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = superhero_app(name=name,
                                      alter_ego=alter_ego,
                                      primary_superhero_ability=primary_superhero_ability,
                                      secondary_superhero_ability=secondary_superhero_ability,
                                      catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheros_app:index'))
    else:
        return render(request, 'superheros_app/create.html')


def kryptonite(request, superheros_id):
    superhero_app.objects.filter(id=superheros_id).delete()
    return HttpResponseRedirect(reverse('superheros_app:index'))

superheros/superheros_app/templates/superheros_app/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Superhero Create</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/superheros_app"> HOME </a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h1>Create A Superhero!</h1>
            <div class="container-fluid">
                <form action="{% url 'superheros_app:create_new_superhero' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                       <label for="name">Name:</label><br>
                        <input type="text" name="name" id="name"><br>
                    </div>
                    <div class="form-group">
                        <label for="name">Alter Ego:</label><br>
                        <input type="text" name="alter_ego" id="alter_ego"><br>
                    </div>
                    <div class="form-group">
                        <label for="name">Primary Superhero ability:</label><br>
                        <input type="text" name="primary_superhero_ability" id="Primary_superhero_ability"><br>
                    </div>
                    <div class="form-group">
                       <label for="name">Secondary Superhero ability:</label><br>
                        <input type="text" name="secondary_superhero_ability" id="Secondary_superhero_ability"><br>
                    </div>
                    <div class="form-group">
                        <label for="name">catchphrase:</label><br>
                        <input type="text" name="catchphrase" id="catchphrase"><br>
                    </div>
                     <input type="submit" value="update!">
                </form>

            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
</body>
</html>

superheros/superheros_app/templates/superheros_app/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Superhero Details</title>
</head>
    <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/superheros_app"> HOME </a>
            </div>
        </div>
    </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>Super Hero:</th>
                                    <th>{{single_superheros_app.name}}</th>
                                </tr>
                                <tr>
                                    <th>Alter Ego:</th>
                                    <th>{{single_superheros_app.alter_ego}}</th>
                                </tr>
                                <tr>
                                    <th>Primary Superhero Ability:</th>
                                    <th>{{single_superheros_app.primary_superhero_ability}}</th>
                                </tr>
                                <tr>
                                    <th>Secondary Superhero Ability:</th>
                                    <th>{{single_superheros_app.secondary_superhero_ability}}</th>
                                </tr>
                                <tr>
                                    <th>Catchphrase:</th>
                                    <th>{{single_superheros_app.catchphrase}}</th>
                                </tr>
                            </table>
        <a href="{% url 'superheros_app:update' single_superheros_app.id %}">Update {{single_superheros_app.name}}'s file.</a><br>
        <a href="{% url 'superheros_app:kryptonite' single_superheros_app.id %}">Remove {{single_superheros_app.name}} from all records.</a>
                        </div>
                    </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </body>
</html>

superheros/superheros_app/templates/superheros_app/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Superhero Index</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'superheros_app:create_new_superhero' %}">Create a Superhero</a>
        </div>
    </div>
</nav>
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="table-responsive">
                        <h1 class="text-center">SUPERHERO CREATOR</h1>
                                                {% load static %}
                        <img src="{% static 'knight-rider-2000x1270-1.jpg' %}" class="img-responsive"
                             alt="knight-rider-2000x1270-1.jpg">
                        <p>"One man can make a difference."</p>
                            <hr>
                        <table class="table table-responsive table-striped table-bordered">
                            <h2 class="text-center">List of Superheros</h2>
                            {% for superhero in all_superheros_app %}
                            <tr>
                                <td ><h3> {{superhero.name}} </h3></td>
                                <td ><a href="{% url 'superheros_app:detail' superhero.id %}">Open file.</a></td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</body>
</html>

superheros/superheros_app/templates/superheros_app/update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Superhero Edit</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/superheros_app"> HOME </a>
        </div>
    </div>
</nav>
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                    <div class="col-md-8">

                            <h1>Update Superhero: {{single_superheros_app.name}}</h1>
                            <hr/>
                            <div class="container-fluid">
                                <form action="{% url 'superheros_app:update' single_superheros_app.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                    <label for="name">Name:</label><br>
                                    <input type="text" name="name" class=form-control"
                                           value="{{single_superheros_app.name}}"
                                           id="name">
                                    </div>
                                    <div class="form-group">
                                    <label for="name">Alter Ego:</label><br>
                                    <input type="text" name="alter_ego" class=form-control"
                                           value="{{single_superheros_app.alter_ego}}"
                                           id="alter_ego">
                                    </div>
                                    <div class="form-group">
                                    <label for="name">Primary Superhero ability:</label><br>
                                    <input type="text" name="primary_superhero_ability" class=form-control"
                                           value="{{single_superheros_app.primary_superhero_ability}}"
                                           id="Primary_superhero_ability">
                                    </div>
                                    <div class="form-group">
                                    <label for="name">Secondary Superhero ability:</label><br>
                                    <input type="text" name="secondary_superhero_ability" class=form-control"
                                           value="{{single_superheros_app.secondary_superhero_ability}}"
                                           id="Secondary_superhero_ability">
                                    </div>
                                    <div class="form-group">
                                    <label for="name">catchphrase:</label><br>
                                    <input type="text" name="catchphrase" class=form-control"
                                           value="{{single_superheros_app.catchphrase}}"
                                           id="catchphrase">
                                    </div>
                                    <input type="submit" value="update!">
                                </form>
                            </div>
                    </div>
                <div class="col-md-2"></div>
            </div>
        </div>
</body>
</html>